definitions:
  domain.IdResponse:
    properties:
      id:
        type: string
    type: object
  domain.Request:
    properties:
      compiler:
        type: string
      program:
        type: string
    type: object
  domain.ResultResponse:
    properties:
      result:
        type: string
    type: object
  domain.StatusResponse:
    properties:
      status:
        $ref: '#/definitions/domain.TaskStatus'
    type: object
  domain.TaskStatus:
    enum:
    - created
    - in_progress
    - ready
    - failed
    type: string
    x-enum-varnames:
    - Created
    - InProgress
    - Ready
    - Failed
host: localhost:8080
info:
  contact: {}
  title: Code Executor API
  version: "1.0"
paths:
  /result/{task_id}:
    get:
      parameters:
      - description: Task ID
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.ResultResponse'
  /status/{task_id}:
    get:
      parameters:
      - description: Task ID
        in: path
        name: task_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.StatusResponse'
  /task:
    post:
      consumes:
      - application/json
      parameters:
      - description: Task data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.IdResponse'
swagger: "2.0"
